### ISSUE TITLE
请问下怎么使用和配置？

### ISSUE THREAD

**Issue by hongyuanyu** [ichuan/filecash-docker#1]
想入坑FIC，但是不清楚怎么配置，想请教下，非常感谢~

qq: 3132389683

**Comment by ichuan** [comment]
> 想入坑FIC，但是不清楚怎么配置，想请教下，非常感谢~
> 
> qq: 3132389683

你好，这个仓库只是运行 filecash 节点来同步区块数据的一个 docker 配置实现。我不了解 FIC 挖矿方面的东西。
